import type { Metadata } from 'next'
import { Suspense } from 'react'
import '../styles/styles.css'
import { Figtree } from 'next/font/google'
import PageFooter from '../components/layout/page-footer'
import PageHeader from '../components/layout/page-header'

const figtreeSans = Figtree({
	variable: '--font-figtree-sans',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${figtreeSans.variable}`}>
				<Suspense fallback={<header className="page-header" />}>
					<PageHeader />
				</Suspense>
				{children}
				<PageFooter />
			</body>
		</html>
	)
}
